[tool.poetry]
name = "django-snacks"
version = "0.1.0"
description = ""
authors = ["Adam Owada <adamowada@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
django = "^3.1"

[tool.poetry.dev-dependencies]
pylint = "^2.6.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
